# Generated by Django 5.1.2 on 2024-10-14 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaoihdDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="taohid/")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ML", "Maulana"),
                            ("SH", "Sheikh"),
                            ("AL", "Alim"),
                            ("UL", "Ulama"),
                            ("MU", "Mufassir"),
                            ("MO", "Moulan"),
                        ],
                        default="ML",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
